spring:
  cloud:
    gateway:
      routes:
        - id: parts-service
          uri: lb://parts-service
          predicates:
            - Path=/api/v1/parts-requests/**
          filters:
            - name: CircuitBreaker
              args:
                name: parts-service
                fallbackUri: forward:/fallback/parts-service