spring:
  application:
    name: trip-service

services:
  billing:
    endpoint: ${BILLING_URL:http://localhost:8081}

    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
