# Application Name
spring.application.name=user-auth-service

# Server Port
server.port=8082

# PostgreSQL Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/as_user_auth_service}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:svc_user_auth_service}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:auth_svc_pass_2024}
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection Pool Configuration
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Firebase Configuration
app.firebase-configuration-file=${APP_FIREBASE_CONFIGURATION_FILE:file:C:/SecureKeys/gear-up/firebase-service-account.json}

# Logging
logging.level.com.gearup.userauthservice=DEBUG
logging.level.org.hibernate.SQL=DEBUG
