apiVersion: v1
kind: ConfigMap
metadata:
  name: tracking-service-config
  namespace: default
data:
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  SPRING_DATASOURCE_DB: "gearup_tracking"
  SERVER_PORT: "8086"
  EUREKA_ENABLED: "true"
  EUREKA_SERVER: "http://service-discovery:8761/eureka/"
