apiVersion: v1
kind: ConfigMap
metadata:
  name: tracking-service-config
  namespace: gearup
data:
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  SPRING_DATASOURCE_DB: "as_tracking_service"
  SERVER_PORT: "8091"
  EUREKA_ENABLED: "true"
  EUREKA_SERVER: "http://service-discovery:8761/eureka/"
