apiVersion: v1
kind: Service
metadata:
  name: tracking-service
  namespace: gearup
  labels:
    app: tracking-service
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: tracking-service
  ports:
    - name: http
      protocol: TCP
      port: 8091
      targetPort: 8091
