apiVersion: v1
kind: ConfigMap
metadata:
  name: REPLACE_SERVICE_NAME-config
  namespace: auto-service-system
data:
  # Put non-sensitive configuration values here, consumed as env vars by the Pod
  application.yml: |
    spring:
      profiles:
        active: "prod"
