-- Enable pgvector extension for vector similarity search (if available)
-- In CI/CD environments without pgvector, this will be handled by V2 migration
DO $$
BEGIN
    CREATE EXTENSION IF NOT EXISTS vector;
EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'pgvector extension not available, will use TEXT fallback in V2 migration';
END $$;

-- Table for storing knowledge base documents with embeddings
CREATE TABLE knowledge_documents (
    id BIGSERIAL PRIMARY KEY,
    content TEXT NOT NULL,
    metadata JSONB,
    source VARCHAR(255) NOT NULL,
    category VARCHAR(100),
    embedding TEXT,  -- Will be converted to vector(768) if pgvector is available
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create index for vector similarity search only if pgvector is available
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'vector') THEN
        CREATE INDEX idx_knowledge_documents_embedding ON knowledge_documents 
        USING hnsw (embedding vector_cosine_ops);
    END IF;
END $$;

-- Create indexes for filtering
CREATE INDEX idx_knowledge_documents_source ON knowledge_documents(source);
CREATE INDEX idx_knowledge_documents_category ON knowledge_documents(category);
CREATE INDEX idx_knowledge_documents_metadata ON knowledge_documents USING GIN(metadata);

-- Table for conversation history
CREATE TABLE conversation_history (
    id BIGSERIAL PRIMARY KEY,
    session_id VARCHAR(255) NOT NULL,
    user_id VARCHAR(255),
    message TEXT NOT NULL,
    sender VARCHAR(50) NOT NULL CHECK (sender IN ('USER', 'BOT', 'SYSTEM', 'user', 'bot', 'system')),
    intent VARCHAR(255),
    metadata JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for conversation history
CREATE INDEX idx_conversation_history_session_id ON conversation_history(session_id);
CREATE INDEX idx_conversation_history_user_id ON conversation_history(user_id);
CREATE INDEX idx_conversation_history_created_at ON conversation_history(created_at DESC);

-- Table for chat sessions
CREATE TABLE chat_sessions (
    id BIGSERIAL PRIMARY KEY,
    session_id VARCHAR(255) UNIQUE NOT NULL,
    user_id VARCHAR(255),
    status VARCHAR(50) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'CLOSED', 'ARCHIVED', 'active', 'closed', 'archived')),
    metadata JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP
);

-- Create indexes for chat sessions
CREATE INDEX idx_chat_sessions_session_id ON chat_sessions(session_id);
CREATE INDEX idx_chat_sessions_user_id ON chat_sessions(user_id);
CREATE INDEX idx_chat_sessions_status ON chat_sessions(status);

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger for knowledge_documents
CREATE TRIGGER update_knowledge_documents_updated_at 
    BEFORE UPDATE ON knowledge_documents
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Trigger for chat_sessions
CREATE TRIGGER update_chat_sessions_updated_at 
    BEFORE UPDATE ON chat_sessions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Comments for documentation
COMMENT ON TABLE knowledge_documents IS 'Stores knowledge base documents with vector embeddings for RAG';
COMMENT ON TABLE conversation_history IS 'Stores all chat messages for conversation tracking and analysis';
COMMENT ON TABLE chat_sessions IS 'Stores chat session metadata and status';
COMMENT ON COLUMN knowledge_documents.embedding IS 'Vector embedding generated by nomic-embed-text model (768 dimensions)';
COMMENT ON COLUMN knowledge_documents.metadata IS 'Additional metadata in JSON format (e.g., tags, authors, version)';
COMMENT ON COLUMN conversation_history.intent IS 'Classified user intent (e.g., booking, status, information)';
