package com.gearup.notificationservice.entity;

public enum NotificationType {
    INVOICE_CREATED,
    INVOICE_UPDATED,
    INVOICE_PAID,
    PAYMENT_COMPLETED,
    TASK_ASSIGNED,
    TASK_COMPLETED,
    APPOINTMENT_REMINDER,
    CUSTOMER_REGISTERED,
    CUSTOMER_KYC_CHANGED,
    USER_REGISTERED,
    ROLE_ASSIGNED,
    VEHICLE_REGISTERED,
    VEHICLE_UPDATED,
    SYSTEM_ALERT,
    GENERAL
}
