package com.gearup.notificationservice.entity;

public enum NotificationType {
    INVOICE_CREATED,
    INVOICE_UPDATED,
    INVOICE_PAID,
    TASK_ASSIGNED,
    TASK_COMPLETED,
    BOOKING_CREATED,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    MAINTENANCE_SCHEDULED,
    MAINTENANCE_COMPLETED,
    APPOINTMENT_REMINDER,
    SYSTEM_ALERT,
    GENERAL
}
