apiVersion: v1
kind: ConfigMap
metadata:
  name: parts-service-config
  namespace: gearup
data:
  application.yml: |
    spring:
      datasource:
        url: jdbc:postgresql://${PARTS_DB_URL}/${PARTS_DB_NAME}
        username: ${PARTS_DB_USERNAME}
        password: ${PARTS_DB_PASSWORD}
      jpa:
        hibernate:
          ddl-auto: validate
      flyway:
        enabled: true
        baselineOnMigrate: true
        
    server:
      port: 8082
      
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics
      endpoint:
        health:
          show-details: always