apiVersion: v1
kind: Secret
metadata:
  name: parts-service-secrets
  namespace: gearup
type: Opaque
data:
  PARTS_DB_USERNAME: cGFydHNfdXNlcg==  # parts_user
  PARTS_DB_PASSWORD: cGFydHNfcGFzc3dvcmQ=  # parts_password