apiVersion: v1
kind: Service
metadata:
  name: parts-service
  namespace: gearup
spec:
  selector:
    app: parts-service
  ports:
    - protocol: TCP
      port: 8093
      targetPort: 8093
  type: ClusterIP